package com.dishanhai.gt_shanhai.common.machine.misc;

import com.gregtechceu.gtceu.api.recipe.GTRecipeType;
import com.gregtechceu.gtceu.common.data.GTRecipeTypes;
import com.gregtechceu.gtceu.common.data.GCyMRecipeTypes;

import org.gtlcore.gtlcore.common.data.GTLRecipeTypes;
import com.gtladd.gtladditions.common.recipe.GTLAddRecipesTypes;
import com.dishanhai.gt_shanhai.api.recipe.DShanhaiRecipeTypes;
import com.dishanhai.gt_shanhai.config.DShanhaiConfig;

import java.util.*;

public class ShanhaiMachineModeMap {

    public static final int TOTAL_MODES = 36;

    private static final GTRecipeType[][] MODE_GROUPS_ORIGINAL = new GTRecipeType[TOTAL_MODES][];
    private static final GTRecipeType[][] MODE_GROUPS_SHUFFLED = new GTRecipeType[TOTAL_MODES][];

    static {
        // ═══ 原版：同类配方聚合 ═══
        MODE_GROUPS_ORIGINAL[0]  = group(GTRecipeTypes.COMPRESSOR_RECIPES, GTRecipeTypes.FORGE_HAMMER_RECIPES, GTLRecipeTypes.NEUTRON_COMPRESSOR_RECIPES, GTLRecipeTypes.ELECTRIC_IMPLOSION_COMPRESSOR_RECIPES);
        MODE_GROUPS_ORIGINAL[1]  = group(GTRecipeTypes.EXTRACTOR_RECIPES, GTRecipeTypes.FERMENTING_RECIPES, GTLRecipeTypes.DISSOLUTION_TREATMENT, GTLRecipeTypes.DIGESTION_TREATMENT);
        MODE_GROUPS_ORIGINAL[2]  = group(GTRecipeTypes.AUTOCLAVE_RECIPES, GTRecipeTypes.FLUID_SOLIDFICATION_RECIPES, GTRecipeTypes.FLUID_HEATER_RECIPES, GTLRecipeTypes.HEAT_EXCHANGER_RECIPES);
        MODE_GROUPS_ORIGINAL[3]  = group(GTRecipeTypes.ORE_WASHER_RECIPES, GTRecipeTypes.THERMAL_CENTRIFUGE_RECIPES, GTRecipeTypes.CENTRIFUGE_RECIPES, GTLRecipeTypes.RARE_EARTH_CENTRIFUGAL_RECIPES);
        MODE_GROUPS_ORIGINAL[4]  = group(GTRecipeTypes.FURNACE_RECIPES, GTRecipeTypes.ALLOY_SMELTER_RECIPES, GTLRecipeTypes.LAVA_FURNACE_RECIPES, GCyMRecipeTypes.ALLOY_BLAST_RECIPES);
        MODE_GROUPS_ORIGINAL[5]  = group(GTRecipeTypes.ARC_FURNACE_RECIPES, GTRecipeTypes.BLAST_RECIPES, GTLRecipeTypes.STELLAR_FORGE_RECIPES, GTLRecipeTypes.DIMENSIONALLY_TRANSCENDENT_PLASMA_FORGE_RECIPES);
        MODE_GROUPS_ORIGINAL[6]  = group(GTRecipeTypes.SIFTER_RECIPES, GTRecipeTypes.ELECTROMAGNETIC_SEPARATOR_RECIPES, GTLRecipeTypes.FLOTATING_BENEFICIATION_RECIPES, GTLRecipeTypes.LARGE_GAS_COLLECTOR_RECIPES);
        MODE_GROUPS_ORIGINAL[7]  = group(GTRecipeTypes.MACERATOR_RECIPES, GTRecipeTypes.LATHE_RECIPES, GTLRecipeTypes.ISA_MILL_RECIPES, GTLRecipeTypes.NANO_FORGE_RECIPES);
        MODE_GROUPS_ORIGINAL[8]  = group(GTRecipeTypes.DISTILLERY_RECIPES, GTRecipeTypes.BREWING_RECIPES, GTLRecipeTypes.DESULFURIZER_RECIPES, GTLRecipeTypes.PETROCHEMICAL_PLANT_RECIPES);
        MODE_GROUPS_ORIGINAL[9]  = group(GTRecipeTypes.PACKER_RECIPES, GTRecipeTypes.CANNER_RECIPES, GTLRecipeTypes.VACUUM_DRYING_RECIPES, GTLRecipeTypes.FUEL_REFINING_RECIPES);
        MODE_GROUPS_ORIGINAL[10] = group(GTRecipeTypes.FUSION_RECIPES, GTLRecipeTypes.HYPER_REACTOR_RECIPES, GTLRecipeTypes.ADVANCED_HYPER_REACTOR_RECIPES, GTLRecipeTypes.LARGE_NAQUADAH_REACTOR_RECIPES);
        MODE_GROUPS_ORIGINAL[11] = group(GTRecipeTypes.IMPLOSION_RECIPES, GTRecipeTypes.VACUUM_RECIPES, GTLRecipeTypes.PLASMA_CONDENSER_RECIPES, GTLRecipeTypes.ATOMIC_ENERGY_EXCITATION_RECIPES);
        MODE_GROUPS_ORIGINAL[12] = group(GTRecipeTypes.LARGE_CHEMICAL_RECIPES, GTRecipeTypes.CHEMICAL_BATH_RECIPES, GTLRecipeTypes.DIMENSIONALLY_TRANSCENDENT_MIXER_RECIPES, GTLRecipeTypes.DISTORT_RECIPES);
        MODE_GROUPS_ORIGINAL[13] = group(GTRecipeTypes.WIREMILL_RECIPES, GTRecipeTypes.BENDER_RECIPES, GTRecipeTypes.EXTRUDER_RECIPES, GTRecipeTypes.FORMING_PRESS_RECIPES);
        MODE_GROUPS_ORIGINAL[14] = group(GTRecipeTypes.ASSEMBLER_RECIPES, GTRecipeTypes.CIRCUIT_ASSEMBLER_RECIPES, GTLRecipeTypes.COMPONENT_ASSEMBLY_LINE_RECIPES, GTLRecipeTypes.PRECISION_ASSEMBLER_RECIPES);
        MODE_GROUPS_ORIGINAL[15] = group(GTRecipeTypes.CUTTER_RECIPES, GTRecipeTypes.LASER_ENGRAVER_RECIPES, GTLRecipeTypes.PRECISION_LASER_ENGRAVER_RECIPES, GTLRecipeTypes.DIMENSIONAL_FOCUS_ENGRAVING_ARRAY_RECIPES);
        MODE_GROUPS_ORIGINAL[16] = group(GTRecipeTypes.ASSEMBLY_LINE_RECIPES, GTLRecipeTypes.SUPRACHRONAL_ASSEMBLY_LINE_RECIPES, GTLRecipeTypes.CIRCUIT_ASSEMBLY_LINE_RECIPES, GTLRecipeTypes.PCB_FACTORY_RECIPES);
        MODE_GROUPS_ORIGINAL[17] = group(GTRecipeTypes.MIXER_RECIPES, GTLRecipeTypes.DEHYDRATOR_RECIPES, GTLRecipeTypes.FUEL_REFINING_RECIPES, GTLRecipeTypes.HEAT_EXCHANGER_RECIPES);
        MODE_GROUPS_ORIGINAL[18] = group(GTRecipeTypes.ELECTROLYZER_RECIPES, GTRecipeTypes.POLARIZER_RECIPES, GTLRecipeTypes.QFT_RECIPES, GTLRecipeTypes.SPS_CRAFTING_RECIPES);
        MODE_GROUPS_ORIGINAL[19] = group(GTLRecipeTypes.LARGE_NAQUADAH_REACTOR_RECIPES, GTLRecipeTypes.FISSION_REACTOR_RECIPES, GTLRecipeTypes.SUPER_PARTICLE_COLLIDER_RECIPES, GTLRecipeTypes.ANNIHILATE_GENERATOR_RECIPES);
        MODE_GROUPS_ORIGINAL[20] = group(GTLRecipeTypes.NANO_FORGE_RECIPES, GTLRecipeTypes.PCB_FACTORY_RECIPES, GTLRecipeTypes.DIMENSIONAL_FOCUS_ENGRAVING_ARRAY_RECIPES, GTLAddRecipesTypes.INSTANCE.getPHOTON_MATRIX_ETCH());
        MODE_GROUPS_ORIGINAL[21] = group(GTLRecipeTypes.PETROCHEMICAL_PLANT_RECIPES, GTLRecipeTypes.DIGESTION_TREATMENT, GTLRecipeTypes.DISSOLUTION_TREATMENT, GTLAddRecipesTypes.INSTANCE.getSPACE_ORE_PROCESSOR());
        MODE_GROUPS_ORIGINAL[22] = group(GTLRecipeTypes.DIMENSIONALLY_TRANSCENDENT_PLASMA_FORGE_RECIPES, GTLAddRecipesTypes.INSTANCE.getFORGE_OF_THE_ANTICHRIST(), GTLRecipeTypes.STELLAR_FORGE_RECIPES, GTLRecipeTypes.NEUTRON_COMPRESSOR_RECIPES);
        MODE_GROUPS_ORIGINAL[23] = group(GTLRecipeTypes.INTEGRATED_ORE_PROCESSOR, GTLRecipeTypes.FRAGMENT_WORLD_COLLECTION, GTLRecipeTypes.MINER_MODULE_RECIPES, GTLAddRecipesTypes.INSTANCE.getSTAR_CORE_STRIPPER());
        MODE_GROUPS_ORIGINAL[24] = group(GTRecipeTypes.GAS_COLLECTOR_RECIPES, GTLRecipeTypes.LARGE_GAS_COLLECTOR_RECIPES, GTLRecipeTypes.LARGE_VOID_MINER_RECIPES, GTLRecipeTypes.BEDROCK_DRILLING_RIG_RECIPES);
        MODE_GROUPS_ORIGINAL[25] = group(GTRecipeTypes.ROCK_BREAKER_RECIPES, GTRecipeTypes.SCANNER_RECIPES, GTLRecipeTypes.FISHING_GROUND_RECIPES, GTLRecipeTypes.LARGE_RECYCLER_RECIPES);
        MODE_GROUPS_ORIGINAL[26] = group(GTLRecipeTypes.GREENHOUSE_RECIPES, GTLRecipeTypes.INCUBATOR_RECIPES, GTLRecipeTypes.SLAUGHTERHOUSE_RECIPES, GTLRecipeTypes.FISHING_GROUND_RECIPES);
        MODE_GROUPS_ORIGINAL[27] = group(GTLRecipeTypes.LARGE_RECYCLER_RECIPES, GTLRecipeTypes.DISASSEMBLY_RECIPES, GTLRecipeTypes.ELEMENT_COPYING_RECIPES);
        MODE_GROUPS_ORIGINAL[28] = group(GTLRecipeTypes.NEUTRON_ACTIVATOR_RECIPES, GTLRecipeTypes.LIGHTNING_PROCESSOR_RECIPES, GTLRecipeTypes.DECAY_HASTENER_RECIPES, GTLRecipeTypes.ATOMIC_ENERGY_EXCITATION_RECIPES);
        MODE_GROUPS_ORIGINAL[29] = group(GTLRecipeTypes.MASS_FABRICATOR_RECIPES, GTLRecipeTypes.MATTER_FABRICATOR_RECIPES, GTLRecipeTypes.SPS_CRAFTING_RECIPES, GTLRecipeTypes.CREATE_AGGREGATION_RECIPES);
        MODE_GROUPS_ORIGINAL[30] = group(GTLAddRecipesTypes.INSTANCE.getBIOLOGICAL_SIMULATION(), GTLAddRecipesTypes.INSTANCE.getANTIENTROPY_CONDENSATION(), GTLRecipeTypes.MAGIC_MANUFACTURER_RECIPES, GTLRecipeTypes.COSMOS_SIMULATION_RECIPES);
        MODE_GROUPS_ORIGINAL[31] = group(GTLRecipeTypes.SPACE_ELEVATOR_RECIPES, GTLAddRecipesTypes.INSTANCE.getSPACE_ORE_PROCESSOR(), GTLRecipeTypes.QFT_RECIPES, GTLRecipeTypes.DISASSEMBLY_RECIPES);
        MODE_GROUPS_ORIGINAL[32] = group(GTRecipeTypes.ASSEMBLY_LINE_RECIPES, GTLRecipeTypes.CIRCUIT_ASSEMBLY_LINE_RECIPES, GTLRecipeTypes.SUPRACHRONAL_ASSEMBLY_LINE_RECIPES, GTLRecipeTypes.COMPONENT_ASSEMBLY_LINE_RECIPES);
        MODE_GROUPS_ORIGINAL[33] = group(DShanhaiRecipeTypes.SPACETIME_DISTORTION, DShanhaiRecipeTypes.PRIMORDIAL_MATTER_RECOMBINATION, DShanhaiRecipeTypes.PRIMORDIAL_CAUSAL_WEAVING, DShanhaiRecipeTypes.PRIMORDIAL_SINGULARITY_INVERSION);
        MODE_GROUPS_ORIGINAL[34] = group(GTRecipeTypes.ASSEMBLY_LINE_RECIPES, GTLRecipeTypes.SUPRACHRONAL_ASSEMBLY_LINE_RECIPES, GTLRecipeTypes.CIRCUIT_ASSEMBLY_LINE_RECIPES, GTLAddRecipesTypes.INSTANCE.getFORGE_OF_THE_ANTICHRIST(), DShanhaiRecipeTypes.SPACETIME_DISTORTION);
        MODE_GROUPS_ORIGINAL[35] = group(GTRecipeTypes.FUSION_RECIPES, GTLRecipeTypes.HYPER_REACTOR_RECIPES, GTLRecipeTypes.ADVANCED_HYPER_REACTOR_RECIPES, GTLRecipeTypes.ANNIHILATE_GENERATOR_RECIPES, DShanhaiRecipeTypes.CHAOS_CRAFTING, DShanhaiRecipeTypes.SEVENTY_TWO_CHANGES);

        // ═══ 打乱版：同类配方分散到不同模式，防止串配方 ═══
        // 每组内4个配方类型来自完全不同的机器类别

        MODE_GROUPS_SHUFFLED[0]  = group(GTRecipeTypes.COMPRESSOR_RECIPES, GTRecipeTypes.LASER_ENGRAVER_RECIPES, GTRecipeTypes.EXTRACTOR_RECIPES, GTLRecipeTypes.LAVA_FURNACE_RECIPES);
        MODE_GROUPS_SHUFFLED[1]  = group(GTRecipeTypes.FORGE_HAMMER_RECIPES, GTRecipeTypes.AUTOCLAVE_RECIPES, GTRecipeTypes.CENTRIFUGE_RECIPES, GTLRecipeTypes.INCUBATOR_RECIPES);
        MODE_GROUPS_SHUFFLED[2]  = group(GTRecipeTypes.FURNACE_RECIPES, GTLRecipeTypes.INTEGRATED_ORE_PROCESSOR, GTLRecipeTypes.VACUUM_DRYING_RECIPES, GTRecipeTypes.LARGE_CHEMICAL_RECIPES);
        MODE_GROUPS_SHUFFLED[3]  = group(GTRecipeTypes.ORE_WASHER_RECIPES, GTRecipeTypes.SIFTER_RECIPES, GTRecipeTypes.BENDER_RECIPES, GTLRecipeTypes.LARGE_NAQUADAH_REACTOR_RECIPES);
        MODE_GROUPS_SHUFFLED[4]  = group(GTRecipeTypes.ARC_FURNACE_RECIPES, GTRecipeTypes.PACKER_RECIPES, GTRecipeTypes.ELECTROLYZER_RECIPES, GTLRecipeTypes.FISHING_GROUND_RECIPES);
        MODE_GROUPS_SHUFFLED[5]  = group(GTRecipeTypes.BLAST_RECIPES, GTLRecipeTypes.GREENHOUSE_RECIPES, GTRecipeTypes.POLARIZER_RECIPES, GTRecipeTypes.WIREMILL_RECIPES);
        MODE_GROUPS_SHUFFLED[6]  = group(GTRecipeTypes.ALLOY_SMELTER_RECIPES, GTLRecipeTypes.DIMENSIONALLY_TRANSCENDENT_MIXER_RECIPES, GTRecipeTypes.LATHE_RECIPES, DShanhaiRecipeTypes.PRIMORDIAL_MATTER_RECOMBINATION);
        MODE_GROUPS_SHUFFLED[7]  = group(GTRecipeTypes.MACERATOR_RECIPES, GTRecipeTypes.FERMENTING_RECIPES, GTRecipeTypes.FLUID_SOLIDFICATION_RECIPES, GTLRecipeTypes.SUPER_PARTICLE_COLLIDER_RECIPES);
        MODE_GROUPS_SHUFFLED[8]  = group(GTRecipeTypes.DISTILLERY_RECIPES, GTRecipeTypes.FORMING_PRESS_RECIPES, GTRecipeTypes.ELECTROMAGNETIC_SEPARATOR_RECIPES, GTLRecipeTypes.LIGHTNING_PROCESSOR_RECIPES);
        MODE_GROUPS_SHUFFLED[9]  = group(GTRecipeTypes.CANNER_RECIPES, GTLRecipeTypes.ANNIHILATE_GENERATOR_RECIPES, GTRecipeTypes.ROCK_BREAKER_RECIPES, GTRecipeTypes.SCANNER_RECIPES);
        MODE_GROUPS_SHUFFLED[10] = group(GTRecipeTypes.FUSION_RECIPES, GTRecipeTypes.CIRCUIT_ASSEMBLER_RECIPES, GTRecipeTypes.BREWING_RECIPES, GTLAddRecipesTypes.INSTANCE.getANTIENTROPY_CONDENSATION());
        MODE_GROUPS_SHUFFLED[11] = group(GTRecipeTypes.IMPLOSION_RECIPES, GTLRecipeTypes.SUPRACHRONAL_ASSEMBLY_LINE_RECIPES, GTLRecipeTypes.DESULFURIZER_RECIPES, DShanhaiRecipeTypes.TAIXU_SMELTING);
        MODE_GROUPS_SHUFFLED[12] = group(GTRecipeTypes.VACUUM_RECIPES, GTLRecipeTypes.FISSION_REACTOR_RECIPES, GTLRecipeTypes.FLOTATING_BENEFICIATION_RECIPES, GTRecipeTypes.WIREMILL_RECIPES);
        MODE_GROUPS_SHUFFLED[13] = group(GTRecipeTypes.ASSEMBLER_RECIPES, GTRecipeTypes.FLUID_HEATER_RECIPES, GTLRecipeTypes.LARGE_GAS_COLLECTOR_RECIPES, GTLRecipeTypes.DIMENSIONAL_FOCUS_ENGRAVING_ARRAY_RECIPES);
        MODE_GROUPS_SHUFFLED[14] = group(GTRecipeTypes.ASSEMBLY_LINE_RECIPES, GTLRecipeTypes.PETROCHEMICAL_PLANT_RECIPES, GTRecipeTypes.CUTTER_RECIPES, GTLRecipeTypes.DEHYDRATOR_RECIPES);
        MODE_GROUPS_SHUFFLED[15] = group(GTLRecipeTypes.CIRCUIT_ASSEMBLY_LINE_RECIPES, GTLRecipeTypes.BEDROCK_DRILLING_RIG_RECIPES, GTLRecipeTypes.PLASMA_CONDENSER_RECIPES, GTLRecipeTypes.DISASSEMBLY_RECIPES);
        MODE_GROUPS_SHUFFLED[16] = group(GTLRecipeTypes.COMPONENT_ASSEMBLY_LINE_RECIPES, GTLRecipeTypes.LARGE_VOID_MINER_RECIPES, GTRecipeTypes.CHEMICAL_BATH_RECIPES, GTLRecipeTypes.ISA_MILL_RECIPES);
        MODE_GROUPS_SHUFFLED[17] = group(GTRecipeTypes.MIXER_RECIPES, GTLRecipeTypes.NEUTRON_ACTIVATOR_RECIPES, GTLRecipeTypes.DISSOLUTION_TREATMENT, GTLRecipeTypes.PCB_FACTORY_RECIPES);
        MODE_GROUPS_SHUFFLED[18] = group(GTLRecipeTypes.NANO_FORGE_RECIPES, GTLRecipeTypes.FUEL_REFINING_RECIPES, GTLRecipeTypes.PRECISION_ASSEMBLER_RECIPES, GTLRecipeTypes.ELECTRIC_IMPLOSION_COMPRESSOR_RECIPES);
        MODE_GROUPS_SHUFFLED[19] = group(GTLAddRecipesTypes.INSTANCE.getFORGE_OF_THE_ANTICHRIST(), GTLRecipeTypes.STELLAR_FORGE_RECIPES, GTLRecipeTypes.LARGE_RECYCLER_RECIPES, GTLRecipeTypes.ATOMIC_ENERGY_EXCITATION_RECIPES);
        MODE_GROUPS_SHUFFLED[20] = group(GTLRecipeTypes.DIMENSIONALLY_TRANSCENDENT_PLASMA_FORGE_RECIPES, GTRecipeTypes.GAS_COLLECTOR_RECIPES, GTLRecipeTypes.DIGESTION_TREATMENT, GTLRecipeTypes.VACUUM_DRYING_RECIPES);
        MODE_GROUPS_SHUFFLED[21] = group(GTLRecipeTypes.HYPER_REACTOR_RECIPES, GTLRecipeTypes.ELEMENT_COPYING_RECIPES, GTRecipeTypes.EXTRUDER_RECIPES, GTRecipeTypes.FORMING_PRESS_RECIPES);
        MODE_GROUPS_SHUFFLED[22] = group(GTLRecipeTypes.ADVANCED_HYPER_REACTOR_RECIPES, GTLRecipeTypes.SPACE_ELEVATOR_RECIPES, GTRecipeTypes.THERMAL_CENTRIFUGE_RECIPES, GTLRecipeTypes.SLAUGHTERHOUSE_RECIPES);
        MODE_GROUPS_SHUFFLED[23] = group(GTLRecipeTypes.QFT_RECIPES, GTLRecipeTypes.FRAGMENT_WORLD_COLLECTION, GTLRecipeTypes.NEUTRON_COMPRESSOR_RECIPES, DShanhaiRecipeTypes.PRIMORDIAL_CAUSAL_WEAVING);
        MODE_GROUPS_SHUFFLED[24] = group(GTLRecipeTypes.SPS_CRAFTING_RECIPES, GTLRecipeTypes.MAGIC_MANUFACTURER_RECIPES, GTRecipeTypes.CHEMICAL_BATH_RECIPES, GTLRecipeTypes.MINER_MODULE_RECIPES);
        MODE_GROUPS_SHUFFLED[25] = group(GTLRecipeTypes.MASS_FABRICATOR_RECIPES, GTLRecipeTypes.RARE_EARTH_CENTRIFUGAL_RECIPES, GTRecipeTypes.BENDER_RECIPES, GTRecipeTypes.FERMENTING_RECIPES);
        MODE_GROUPS_SHUFFLED[26] = group(GTLRecipeTypes.MATTER_FABRICATOR_RECIPES, GTLRecipeTypes.PRECISION_LASER_ENGRAVER_RECIPES, GTRecipeTypes.CENTRIFUGE_RECIPES, GTLRecipeTypes.HEAT_EXCHANGER_RECIPES);
        MODE_GROUPS_SHUFFLED[27] = group(GTLRecipeTypes.DECAY_HASTENER_RECIPES, GTLRecipeTypes.ATOMIC_ENERGY_EXCITATION_RECIPES, GTRecipeTypes.GAS_COLLECTOR_RECIPES, GTLRecipeTypes.CREATE_AGGREGATION_RECIPES);
        MODE_GROUPS_SHUFFLED[28] = group(GTLRecipeTypes.DISTORT_RECIPES, GTRecipeTypes.LASER_ENGRAVER_RECIPES, GTRecipeTypes.THERMAL_CENTRIFUGE_RECIPES, DShanhaiRecipeTypes.PRIMORDIAL_SINGULARITY_INVERSION);
        MODE_GROUPS_SHUFFLED[29] = group(GTLAddRecipesTypes.INSTANCE.getSPACE_ORE_PROCESSOR(), GTRecipeTypes.POLARIZER_RECIPES, GTLRecipeTypes.AGGREGATION_DEVICE_RECIPES, GTRecipeTypes.LATHE_RECIPES);
        MODE_GROUPS_SHUFFLED[30] = group(GTLAddRecipesTypes.INSTANCE.getBIOLOGICAL_SIMULATION(), GTLRecipeTypes.COSMOS_SIMULATION_RECIPES, GCyMRecipeTypes.ALLOY_BLAST_RECIPES, GTLRecipeTypes.HEAT_EXCHANGER_RECIPES);
        MODE_GROUPS_SHUFFLED[31] = group(GTLAddRecipesTypes.INSTANCE.getSTAR_CORE_STRIPPER(), GTLRecipeTypes.HEAT_EXCHANGER_RECIPES, DShanhaiRecipeTypes.PRIMORDIAL_CAUSAL_WEAVING, GTRecipeTypes.SCANNER_RECIPES);
        MODE_GROUPS_SHUFFLED[32] = group(GTLAddRecipesTypes.INSTANCE.getPHOTON_MATRIX_ETCH(), GTRecipeTypes.EXTRACTOR_RECIPES, GTRecipeTypes.IMPLOSION_RECIPES, GTRecipeTypes.ROCK_BREAKER_RECIPES);
        MODE_GROUPS_SHUFFLED[33] = group(DShanhaiRecipeTypes.SPACETIME_DISTORTION, DShanhaiRecipeTypes.PRIMORDIAL_POWER_GENERATOR, DShanhaiRecipeTypes.GRAVITATIONAL_WAVE_PRODUCTION, GTLAddRecipesTypes.INSTANCE.getPHOTON_MATRIX_ETCH());
        MODE_GROUPS_SHUFFLED[34] = group(GTRecipeTypes.ASSEMBLY_LINE_RECIPES, GTLRecipeTypes.SUPRACHRONAL_ASSEMBLY_LINE_RECIPES, GTLRecipeTypes.PETROCHEMICAL_PLANT_RECIPES, DShanhaiRecipeTypes.MATTER_MODULE_CASTING);
        MODE_GROUPS_SHUFFLED[35] = group(GTRecipeTypes.FUSION_RECIPES, DShanhaiRecipeTypes.CHAOS_CRAFTING, DShanhaiRecipeTypes.SEVENTY_TWO_CHANGES, DShanhaiRecipeTypes.PRIMORDIAL_BIOLOGICAL_CORE);
    }

    private static GTRecipeType[][] active() {
        return DShanhaiConfig.COMMON.nineIndustrialShuffle.get()
            ? MODE_GROUPS_SHUFFLED : MODE_GROUPS_ORIGINAL;
    }

    public static GTRecipeType[] getRecipeTypes(int mode) {
        if (mode < 0 || mode >= TOTAL_MODES) return new GTRecipeType[0];
        GTRecipeType[][] g = active();
        return g[mode] != null ? g[mode] : new GTRecipeType[0];
    }

    /** 返回模式对应的显示用 GTRecipeType（带水浒传翻译名，供 Jade 机器模式展示） */
    public static GTRecipeType getModeDisplayType(int mode) {
        if (mode < 0 || mode >= TOTAL_MODES) return null;
        return com.dishanhai.gt_shanhai.api.recipe.DShanhaiRecipeTypes.NINE_INDUSTRIAL_MODES[mode];
    }

    public static GTRecipeType[] getAllRecipeTypes() {
        Set<GTRecipeType> set = new LinkedHashSet<>();
        for (GTRecipeType[] group : active()) {
            if (group != null) Collections.addAll(set, group);
        }
        return set.toArray(new GTRecipeType[0]);
    }

    public static GTRecipeType[] getPrimaryTypes() {
        GTRecipeType[] result = new GTRecipeType[TOTAL_MODES];
        GTRecipeType[][] g = active();
        for (int i = 0; i < TOTAL_MODES; i++) {
            result[i] = g[i] != null && g[i].length > 0 ? g[i][0] : null;
        }
        return result;
    }

    public static int getNextMode(int current) { return (current + 1) % TOTAL_MODES; }

    @SafeVarargs
    private static GTRecipeType[] group(GTRecipeType... types) {
        LinkedHashSet<GTRecipeType> set = new LinkedHashSet<>();
        for (GTRecipeType t : types) { if (t != null) set.add(t); }
        return set.toArray(new GTRecipeType[0]);
    }

    private ShanhaiMachineModeMap() {}
}
