package com.dishanhai.gt_shanhai.common.machine.structure;

/*** aisles 30~35 */
public class BHCData2 {
    public static final String[] D31 = {
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "              AACCCAA              ",
        "              AA   AA              ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                 D                 ",
        "                DBD                ",
        "                 D                 ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "              AACCCAA              ",
        "              AA   AA              ",
        "                                   ",
        "                                   ",
        "                                   ",
    };

    public static final String[] D32 = {
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AACCCAA              ",
        "              AA   AA              ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                DBD                ",
        "                BBB                ",
        "                DBD                ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "              AACCCAA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
    };

    public static final String[] D33 = {
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AACCCAA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "                                   ",
        "                                   ",
        "                AAA                ",
        "               A   A               ",
        "              A DBD A              ",
        "              A BBB A              ",
        "              A DBD A              ",
        "               A   A               ",
        "                AAA                ",
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AACCCAA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
    };

    public static final String[] D34 = {
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AACCCAA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AABBBAA              ",
        "              ABBBBBA              ",
        "              BBBBBBB              ",
        "              BBBBBBB              ",
        "              BBBBBBB              ",
        "              ABBBBBA              ",
        "              AABBBAA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AACCCAA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
    };

    public static final String[] D35 = {
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AACCCAA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AAAAAAA              ",
        "              AAAEAAA              ",
        "              AAAAAAA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AACCCAA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
    };

    public static final String[] D36 = {
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "              AACCCAA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AACCCAA              ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
    };

}