package com.dishanhai.gt_shanhai.common.machine.structure;

/*** aisles 0~29 */
public class BHCData1 {
    public static final String[] D1 = {
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
    };

    public static final String[] D2 = {
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "              AACCCAA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AACCCAA              ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
    };

    public static final String[] D3 = {
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AACCCAA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AAAAAAA              ",
        "              AAAEAAA              ",
        "              AAAAAAA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AACCCAA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
    };

    public static final String[] D4 = {
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AACCCAA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AABBBAA              ",
        "              ABBBBBA              ",
        "              BBBBBBB              ",
        "              BBBBBBB              ",
        "              BBBBBBB              ",
        "              ABBBBBA              ",
        "              AABBBAA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AACCCAA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
    };

    public static final String[] D5 = {
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AACCCAA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "                                   ",
        "                                   ",
        "                AAA                ",
        "               A   A               ",
        "              A DBD A              ",
        "              A BBB A              ",
        "              A DBD A              ",
        "               A   A               ",
        "                AAA                ",
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AACCCAA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
    };

    public static final String[] D6 = {
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "              AA   AA              ",
        "              AACCCAA              ",
        "              AA   AA              ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                DBD                ",
        "                BBB                ",
        "                DBD                ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "              AACCCAA              ",
        "              AA   AA              ",
        "              AA   AA              ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
    };

    public static final String[] D7 = {
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "              AACCCAA              ",
        "              AA   AA              ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                 D                 ",
        "                DBD                ",
        "                 D                 ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "              AACCCAA              ",
        "              AA   AA              ",
        "                                   ",
        "                                   ",
        "                                   ",
    };

    public static final String[] D8 = {
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "              AABBBAA              ",
        "              AABBBAA              ",
        "              AABBBAA              ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                 D                 ",
        "                DBD                ",
        "                 D                 ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "              AABBBAA              ",
        "              AABBBAA              ",
        "              AABBBAA              ",
        "                                   ",
        "                                   ",
    };

    public static final String[] D9 = {
        "                                   ",
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "            BBAAAAAAABB            ",
        "            BBAAAAAAABB            ",
        "            BBAAAAAAABB            ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                 B                 ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "            BBAAAAAAABB            ",
        "            BBAAAAAAABB            ",
        "            BBAAAAAAABB            ",
        "              AA   AA              ",
        "                                   ",
    };

    public static final String[] D10 = {
        "                                   ",
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "           BAAAAAAAAAAAB           ",
        "           BAAAAAAAAAAAB           ",
        "           BAAAAAAAAAAAB           ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                 B                 ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "           BAAAAAAAAAAAB           ",
        "           BAAAAAAAAAAAB           ",
        "           BAAAAAAAAAAAB           ",
        "              AA   AA              ",
        "                                   ",
    };

    public static final String[] D11 = {
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "             AAA   AAA             ",
        "          BAAAAAAAAAAAAAB          ",
        "          BAAAAAAAAAAAAAB          ",
        "          BAAAAAAAAAAAAAB          ",
        "          BB           BB          ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "          BB           BB          ",
        "          BAAAAAAAAAAAAAB          ",
        "          BAAAAAAAAAAAAAB          ",
        "          BAAAAAAAAAAAAAB          ",
        "             AAA   AAA             ",
        "              AA   AA              ",
    };

    public static final String[] D12 = {
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "             AAA   AAA             ",
        "         BAAAAAAAAAAAAAAAB         ",
        "         BAAAAAAAAAAAAAAAB         ",
        "         BAAAAAAAAAAAAAAAB         ",
        "         BBBB  AAAAA  BBBB         ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "         BBBB  AAAAA  BBBB         ",
        "         BAAAAAAAAAAAAAAAB         ",
        "         BAAAAAAAAAAAAAAAB         ",
        "         BAAAAAAAAAAAAAAAB         ",
        "             AAA   AAA             ",
        "              AA   AA              ",
    };

    public static final String[] D13 = {
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "            AAAA   AAAA            ",
        "        BAAAAAAAAAAAAAAAAAB        ",
        "        BAAAAAAAAAAAAAAAAAB        ",
        "        BAAAAAAAAAAAAAAAAAB        ",
        "         BBBBAA     AABBBB         ",
        "           BBB AAAAA BBB           ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "           BBB AAAAA BBB           ",
        "         BBBBAA     AABBBB         ",
        "        BAAAAAAAAAAAAAAAAAB        ",
        "        BAAAAAAAAAAAAAAAAAB        ",
        "        BAAAAAAAAAAAAAAAAAB        ",
        "            AAAA   AAAA            ",
        "              AA   AA              ",
    };

    public static final String[] D14 = {
        "                                   ",
        "                                   ",
        "             AAA   AAA             ",
        "           AAAAA   AAAAA           ",
        "       BAAAAAAABBBBBAAAAAAAB       ",
        "       BAAAAAAABBBBBAAAAAAAB       ",
        "       BAAAAAAABBBBBAAAAAAAB       ",
        "          BBA         ABB          ",
        "           BBAA     AABB           ",
        "            BBBAAAAABBB            ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "            BBBAAAAABBB            ",
        "           BBAA     AABB           ",
        "          BBA         ABB          ",
        "       BAAAAAAABBBBBAAAAAAAB       ",
        "       BAAAAAAABBBBBAAAAAAAB       ",
        "       BAAAAAAABBBBBAAAAAAAB       ",
        "           AAAAA   AAAAA           ",
        "             AAA   AAA             ",
    };

    public static final String[] D15 = {
        "                                   ",
        "                                   ",
        "            AAA     AAA            ",
        "         AAAAAA     AAAAAA         ",
        "       BAAAAAAB     BAAAAAAB       ",
        "       BAAAAAABAAAAABAAAAAAB       ",
        "       BAAAAAAB     BAAAAAAB       ",
        "           A           A           ",
        "           BA         AB           ",
        "            BBA     ABB            ",
        "             BBAAAAABB             ",
        "              BAAAAAB              ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "              BAAAAAB              ",
        "             BBAAAAABB             ",
        "            BBA     ABB            ",
        "           BA         AB           ",
        "           A           A           ",
        "       BAAAAAAB     BAAAAAAB       ",
        "       BAAAAAABAAAAABAAAAAAB       ",
        "       BAAAAAAB     BAAAAAAB       ",
        "         AAAAAA     AAAAAA         ",
        "            AAA     AAA            ",
    };

    public static final String[] D16 = {
        "                                   ",
        "                                   ",
        "         AAAAA       AAAAA         ",
        "       AAAAAAA       AAAAAAA       ",
        "      AAAAAAAB       BAAAAAAA      ",
        "     AAAAAAAABAAAAAAABAAAAAAAA     ",
        "    AAAAAAAAAB       BAAAAAAAAA    ",
        "   AAA     A           A     AAA   ",
        "   AA       A         A       AA   ",
        "  AAA       BA       AB       AAA  ",
        "  AA         BA     AB         AA  ",
        "  AA         BA     AB         AA  ",
        " AAA          BBAAABB          AAA ",
        " AA            BAAAB            AA ",
        " AA             BBB             AA ",
        " AA                             AA ",
        "AAA                             AAA",
        "AABA                           ABAA",
        "AABA                           ABAA",
        "AABA                           ABAA",
        "AAA                             AAA",
        " AA                             AA ",
        " AA             BBB             AA ",
        " AA            BAAAB            AA ",
        " AAA          BBAAABB          AAA ",
        "  AA         BA     AB         AA  ",
        "  AA         BA     AB         AA  ",
        "  AAA       BA       AB       AAA  ",
        "   AA       A         A       AA   ",
        "   AAA     A           A     AAA   ",
        "    AAAAAAAAAB       BAAAAAAAAA    ",
        "     AAAAAAAABAAAAAAABAAAAAAAA     ",
        "      AAAAAAAB       BAAAAAAA      ",
        "       AAAAAAA       AAAAAAA       ",
        "         AAAAA       AAAAA         ",
    };

    public static final String[] D17 = {
        "                                   ",
        "                                   ",
        "         AAAA         AAAA         ",
        "       AAAAAA         AAAAAA       ",
        "      AAAAAAB   BBB   BAAAAAA      ",
        "     AAAAAAABAAAAAAAAABAAAAAAA     ",
        "    AAAAAAAAB         BAAAAAAAA    ",
        "   AAA    A             A    AAA   ",
        "   AA      A           A      AA   ",
        "  AAA       A         A       AAA  ",
        "  AA         A       A         AA  ",
        "  AA         A       A         AA  ",
        " AAA          BA   AB          AAA ",
        " AA           BA   AB           AA ",
        " AA            BAAAB            AA ",
        " AA             BBB             AA ",
        "AABA                           ABAA",
        "AAB                             BAA",
        "AAB                             BAA",
        "AAB                             BAA",
        "AABA                           ABAA",
        " AA             BBB             AA ",
        " AA            BAAAB            AA ",
        " AA           BA   AB           AA ",
        " AAA          BA   AB          AAA ",
        "  AA         A       A         AA  ",
        "  AA         A       A         AA  ",
        "  AAA       A         A       AAA  ",
        "   AA      A           A      AA   ",
        "   AAA    A             A    AAA   ",
        "    AAAAAAAAB         BAAAAAAAA    ",
        "     AAAAAAABAAAAAAAAABAAAAAAA     ",
        "      AAAAAAB   BBB   BAAAAAA      ",
        "       AAAAAA         AAAAAA       ",
        "         AAAA         AAAA         ",
    };

    public static final String[] D18 = {
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "      BAAAAAB  B   B  BAAAAAB      ",
        "      BAAAAABAAAAAAAAABAAAAAB      ",
        "     CBAAAAAB         BAAAAABC     ",
        "          A             A          ",
        "    C      A           A      C    ",
        "            A         A            ",
        "   C         A       A         C   ",
        "             A       A             ",
        "  C           A     A           C  ",
        "              A     A              ",
        " C            BAAAAAB            C ",
        "  BA           B   B           AB  ",
        "C B                             B C",
        " ABDD                         DDBA ",
        " ABBBDD                     DDBBBA ",
        " ABDD                         DDBA ",
        "C B                             B C",
        "  BA           B   B           AB  ",
        " C            BAAAAAB            C ",
        "              A     A              ",
        "  C           A     A           C  ",
        "             A       A             ",
        "   C         A       A         C   ",
        "            A         A            ",
        "    C      A           A      C    ",
        "          A             A          ",
        "     CBAAAAAB         BAAAAABC     ",
        "      BAAAAABAAAAAAAAABAAAAAB      ",
        "      BAAAAAB  B   B  BAAAAAB      ",
        "                                   ",
        "                                   ",
    };

    public static final String[] D19 = {
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "      BAAAAAB  B   B  BAAAAAB      ",
        "      BAAAAABAAAAAAAAABAAAAAB      ",
        "     CBAAAA B         BAAAAABC     ",
        "          A             ~          ",
        "    C      A           A      C    ",
        "            A         A            ",
        "   C         A       A         C   ",
        "             A       A             ",
        "  C           A     A           C  ",
        "              A     A              ",
        " C            BAAAAAB            C ",
        "  BA           B   B           AB  ",
        "C B                             B C",
        " ABBBDD                     DDBBBA ",
        " EBBBBBBB                 BBBBBBBE ",
        " ABBBDD                     DDBBBA ",
        "C B                             B C",
        "  BA           B   B           AB  ",
        " C            BAAAAAB            C ",
        "              A     A              ",
        "  C           A     A           C  ",
        "             A       A             ",
        "   C         A       A         C   ",
        "            A         A            ",
        "    C      A           A      C    ",
        "          A             A          ",
        "     CBAAAAAB         BAAAAABC     ",
        "      BAAAAABAAAAAAAAABAAAAAB      ",
        "      BAAAAAB  B   B  BAAAAAB      ",
        "                                   ",
        "                                   ",
    };

    public static final String[] D20 = {
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "      BAAAAAB  B   B  BAAAAAB      ",
        "      BAAAAABAAAAAAAAABAAAAAB      ",
        "     CBAAAAAB         BAAAAABC     ",
        "          A             A          ",
        "    C      A           A      C    ",
        "            A         A            ",
        "   C         A       A         C   ",
        "             A       A             ",
        "  C           A     A           C  ",
        "              A     A              ",
        " C            BAAAAAB            C ",
        "  BA           B   B           AB  ",
        "C B                             B C",
        " ABDD                         DDBA ",
        " ABBBDD                     DDBBBA ",
        " ABDD                         DDBA ",
        "C B                             B C",
        "  BA           B   B           AB  ",
        " C            BAAAAAB            C ",
        "              A     A              ",
        "  C           A     A           C  ",
        "             A       A             ",
        "   C         A       A         C   ",
        "            A         A            ",
        "    C      A           A      C    ",
        "          A             A          ",
        "     CBAAAAAB         BAAAAABC     ",
        "      BAAAAABAAAAAAAAABAAAAAB      ",
        "      BAAAAAB  B   B  BAAAAAB      ",
        "                                   ",
        "                                   ",
    };

    public static final String[] D21 = {
        "                                   ",
        "                                   ",
        "         AAAA         AAAA         ",
        "       AAAAAA         AAAAAA       ",
        "      AAAAAAB   BBB   BAAAAAA      ",
        "     AAAAAAABAAAAAAAAABAAAAAAA     ",
        "    AAAAAAAAB         BAAAAAAAA    ",
        "   AAA    A             A    AAA   ",
        "   AA      A           A      AA   ",
        "  AAA       A         A       AAA  ",
        "  AA         A       A         AA  ",
        "  AA         A       A         AA  ",
        " AAA          BA   AB          AAA ",
        " AA           BA   AB           AA ",
        " AA            BAAAB            AA ",
        " AA             BBB             AA ",
        "AABA                           ABAA",
        "AAB                             BAA",
        "AAB                             BAA",
        "AAB                             BAA",
        "AABA                           ABAA",
        " AA             BBB             AA ",
        " AA            BAAAB            AA ",
        " AA           BA   AB           AA ",
        " AAA          BA   AB          AAA ",
        "  AA         A       A         AA  ",
        "  AA         A       A         AA  ",
        "  AAA       A         A       AAA  ",
        "   AA      A           A      AA   ",
        "   AAA    A             A    AAA   ",
        "    AAAAAAAAB         BAAAAAAAA    ",
        "     AAAAAAABAAAAAAAAABAAAAAAA     ",
        "      AAAAAAB   BBB   BAAAAAA      ",
        "       AAAAAA         AAAAAA       ",
        "         AAAA         AAAA         ",
    };

    public static final String[] D22 = {
        "                                   ",
        "                                   ",
        "         AAAAA       AAAAA         ",
        "       AAAAAAA       AAAAAAA       ",
        "      AAAAAAAB       BAAAAAAA      ",
        "     AAAAAAAABAAAAAAABAAAAAAAA     ",
        "    AAAAAAAAAB       BAAAAAAAAA    ",
        "   AAA     A           A     AAA   ",
        "   AA       A         A       AA   ",
        "  AAA       BA       AB       AAA  ",
        "  AA         BA     AB         AA  ",
        "  AA         BA     AB         AA  ",
        " AAA          BBAAABB          AAA ",
        " AA            BAAAB            AA ",
        " AA             BBB             AA ",
        " AA                             AA ",
        "AAA                             AAA",
        "AABA                           ABAA",
        "AABA                           ABAA",
        "AABA                           ABAA",
        "AAA                             AAA",
        " AA                             AA ",
        " AA             BBB             AA ",
        " AA            BAAAB            AA ",
        " AAA          BBAAABB          AAA ",
        "  AA         BA     AB         AA  ",
        "  AA         BA     AB         AA  ",
        "  AAA       BA       AB       AAA  ",
        "   AA       A         A       AA   ",
        "   AAA     A           A     AAA   ",
        "    AAAAAAAAAB       BAAAAAAAAA    ",
        "     AAAAAAAABAAAAAAABAAAAAAAA     ",
        "      AAAAAAAB       BAAAAAAA      ",
        "       AAAAAAA       AAAAAAA       ",
        "         AAAAA       AAAAA         ",
    };

    public static final String[] D23 = {
        "                                   ",
        "                                   ",
        "            AAA     AAA            ",
        "         AAAAAA     AAAAAA         ",
        "       BAAAAAAB     BAAAAAAB       ",
        "       BAAAAAABAAAAABAAAAAAB       ",
        "       BAAAAAAB     BAAAAAAB       ",
        "           A           A           ",
        "           BA         AB           ",
        "            BBA     ABB            ",
        "             BBAAAAABB             ",
        "              BAAAAAB              ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "              BAAAAAB              ",
        "             BBAAAAABB             ",
        "            BBA     ABB            ",
        "           BA         AB           ",
        "           A           A           ",
        "       BAAAAAAB     BAAAAAAB       ",
        "       BAAAAAABAAAAABAAAAAAB       ",
        "       BAAAAAAB     BAAAAAAB       ",
        "         AAAAAA     AAAAAA         ",
        "            AAA     AAA            ",
    };

    public static final String[] D24 = {
        "                                   ",
        "                                   ",
        "             AAA   AAA             ",
        "           AAAAA   AAAAA           ",
        "       BAAAAAAABBBBBAAAAAAAB       ",
        "       BAAAAAAABBBBBAAAAAAAB       ",
        "       BAAAAAAABBBBBAAAAAAAB       ",
        "          BBA         ABB          ",
        "           BBAA     AABB           ",
        "            BBBAAAAABBB            ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "            BBBAAAAABBB            ",
        "           BBAA     AABB           ",
        "          BBA         ABB          ",
        "       BAAAAAAABBBBBAAAAAAAB       ",
        "       BAAAAAAABBBBBAAAAAAAB       ",
        "       BAAAAAAABBBBBAAAAAAAB       ",
        "           AAAAA   AAAAA           ",
        "             AAA   AAA             ",
    };

    public static final String[] D25 = {
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "            AAAA   AAAA            ",
        "        BAAAAAAAAAAAAAAAAAB        ",
        "        BAAAAAAAAAAAAAAAAAB        ",
        "        BAAAAAAAAAAAAAAAAAB        ",
        "         BBBBAA     AABBBB         ",
        "           BBB AAAAA BBB           ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "           BBB AAAAA BBB           ",
        "         BBBBAA     AABBBB         ",
        "        BAAAAAAAAAAAAAAAAAB        ",
        "        BAAAAAAAAAAAAAAAAAB        ",
        "        BAAAAAAAAAAAAAAAAAB        ",
        "            AAAA   AAAA            ",
        "              AA   AA              ",
    };

    public static final String[] D26 = {
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "             AAA   AAA             ",
        "         BAAAAAAAAAAAAAAAB         ",
        "         BAAAAAAAAAAAAAAAB         ",
        "         BAAAAAAAAAAAAAAAB         ",
        "         BBBB  AAAAA  BBBB         ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "         BBBB  AAAAA  BBBB         ",
        "         BAAAAAAAAAAAAAAAB         ",
        "         BAAAAAAAAAAAAAAAB         ",
        "         BAAAAAAAAAAAAAAAB         ",
        "             AAA   AAA             ",
        "              AA   AA              ",
    };

    public static final String[] D27 = {
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "             AAA   AAA             ",
        "          BAAAAAAAAAAAAAB          ",
        "          BAAAAAAAAAAAAAB          ",
        "          BAAAAAAAAAAAAAB          ",
        "          BB           BB          ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "          BB           BB          ",
        "          BAAAAAAAAAAAAAB          ",
        "          BAAAAAAAAAAAAAB          ",
        "          BAAAAAAAAAAAAAB          ",
        "             AAA   AAA             ",
        "              AA   AA              ",
    };

    public static final String[] D28 = {
        "                                   ",
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "           BAAAAAAAAAAAB           ",
        "           BAAAAAAAAAAAB           ",
        "           BAAAAAAAAAAAB           ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                 B                 ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "           BAAAAAAAAAAAB           ",
        "           BAAAAAAAAAAAB           ",
        "           BAAAAAAAAAAAB           ",
        "              AA   AA              ",
        "                                   ",
    };

    public static final String[] D29 = {
        "                                   ",
        "                                   ",
        "                                   ",
        "              AA   AA              ",
        "            BBAAAAAAABB            ",
        "            BBAAAAAAABB            ",
        "            BBAAAAAAABB            ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                 B                 ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "            BBAAAAAAABB            ",
        "            BBAAAAAAABB            ",
        "            BBAAAAAAABB            ",
        "              AA   AA              ",
        "                                   ",
    };

    public static final String[] D30 = {
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "              AABBBAA              ",
        "              AABBBAA              ",
        "              AABBBAA              ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                 D                 ",
        "                DBD                ",
        "                 D                 ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "                                   ",
        "              AABBBAA              ",
        "              AABBBAA              ",
        "              AABBBAA              ",
        "                                   ",
        "                                   ",
    };

}