package com.dishanhai.gt_shanhai.common.machine.structure;

import com.dishanhai.gt_shanhai.api.DShanhaiMBParser;
import com.gregtechceu.gtceu.api.machine.MultiblockMachineDefinition;
import com.gregtechceu.gtceu.api.machine.multiblock.PartAbility;
import com.gregtechceu.gtceu.api.pattern.BlockPattern;
import com.gregtechceu.gtceu.api.pattern.Predicates;
import com.gregtechceu.gtceu.api.pattern.TraceabilityPredicate;
import com.gregtechceu.gtceu.api.pattern.util.RelativeDirection;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraft.resources.ResourceLocation;

public class BHCStructure {
    private static Block b(String id) { return ForgeRegistries.BLOCKS.getValue(new ResourceLocation(id)); }
    private static final Block A=b("gtceu:high_power_casing"),B=b("gtlcore:dimensionally_transcendent_casing"),C=b("kubejs:dimensional_bridge_casing"),D=b("kubejs:dimensional_stability_casing"),E=b("gtlcore:dimension_injection_casing"),F=b("kubejs:spacetime_compression_field_generator"),G=b("gtlcore:molecular_casing"),J=b("kubejs:dimension_creation_casing"),K=b("kubejs:create_aggregatione_core"),L=b("gt_shanhai:active_neutron_casing"),M=b("gtlcore:create_casing");

    // A/H/I 都可挂载仓室 (INPUT_ENERGY + IMPORT/EXPORT ITEMS/FLUIDS)
    private static final TraceabilityPredicate CASING_A = Predicates.blocks(A)
        .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setPreviewCount(1))
        .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
        .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
        .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
        .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setPreviewCount(1));

    public static BlockPattern createPattern(MultiblockMachineDefinition d) {
        return DShanhaiMBParser.parseRaw(DATA, ch -> switch (ch) {
            case 'A' -> CASING_A;
            case 'B' -> Predicates.blocks(B); case 'C' -> Predicates.blocks(C);
            case 'D' -> Predicates.blocks(D); case 'E' -> Predicates.blocks(E);
            case 'F' -> Predicates.blocks(F); case 'G' -> Predicates.blocks(G);
            case 'H' -> CASING_A;  // 原硬编码 ME export buffer → 通用仓室位
            case 'I' -> CASING_A;  // 原硬编码 ME dual hatch → 通用仓室位
            case 'J' -> Predicates.blocks(J); case 'K' -> Predicates.blocks(K);
            case 'L' -> Predicates.blocks(L); case 'M' -> Predicates.blocks(M);
            case '~' -> Predicates.controller(Predicates.blocks(d.getBlock()));
            default -> Predicates.any();
        }, RelativeDirection.FRONT, RelativeDirection.RIGHT, RelativeDirection.UP);
    }
    private static final String DATA = """
            ,,,,,,,,,,                AA   AA,                AA   AA,                AA   AA,               AAA   AAA,              AAA     AAA,           AAAAA       AAAAA,           AAAA         AAAA,,,,           AAAA         AAAA,           AAAAA       AAAAA,              AAA     AAA,               AAA   AAA,                AA   AA,                AA   AA,                AA   AA,,,,,,,,,,
            ,,,,,,,,                AA   AA,                AA   AA,               AAA   AAA,               AAA   AAA,              AAAA   AAAA,             AAAAA   AAAAA,           AAAAAA     AAAAAA,         AAAAAAA       AAAAAAA,         AAAAAA         AAAAAA,,,,         AAAAAA         AAAAAA,         AAAAAAA       AAAAAAA,           AAAAAA     AAAAAA,             AAAAA   AAAAA,              AAAA   AAAA,               AAA   AAA,               AAA   AAA,                AA   AA,                AA   AA,,,,,,,,
            ,,,,,,,                AABBBAA,              BBAAAAAAABB,             BAAAAAAAAAAAB,            BAAAAAAAAAAAAAB,           BAAAAAAAAAAAAAAAB,          BAAAAAAAAAAAAAAAAAB,         BAAAAAAABBBBBAAAAAAAB,         BAAAAAABCDDDCBAAAAAAB,        AAAAAAABCEEEEECBAAAAAAA,        AAAAAABCEEBBBEECBAAAAAA,        BAAAAABDEBFFFBEDBAAAAAB,        BAAAAABDEBFFFBEDBAAAAAB,        BAAAAABDEBFFFBEDBAAAAAB,        AAAAAABCEEBBBEECBAAAAAA,        AAAAAAABCEEEEECBAAAAAAA,         BAAAAAABCDDDCBAAAAAAB,         BAAAAAAABBBBBAAAAAAAB,          BAAAAAAAAAAAAAAAAAB,           BAAAAAAAAAAAAAAAB,            BAAAAAAAAAAAAAB,             BAAAAAAAAAAAB,              BBAAAAAAABB,                AABBBAA,,,,,,,
            ,,,,,,                AA   AA,                AABBBAA,              BBAAAAAAABB,             BAAAAAAAAAAAB,            BAAAAAAAAAAAAAB,           BAAAAAAAAAAAAAAAB,          BAAAAAAAAAAAAAAAAAB,         BAAAAAAABBBBBAAAAAAAB,         BAAAAAABAAAAABAAAAAAB,       AAAAAAAABAAAAAAABAAAAAAAA,       AAAAAAABAAAAAAAAABAAAAAAA,        BAAAAABAAAAAAAAABAAAAAB,        BAAAAABAAAAAAAAABAAAAAB,        BAAAAABAAAAAAAAABAAAAAB,       AAAAAAABAAAAAAAAABAAAAAAA,       AAAAAAAABAAAAAAABAAAAAAAA,         BAAAAAABAAAAABAAAAAAB,         BAAAAAAABBBBBAAAAAAAB,          BAAAAAAAAAAAAAAAAAB,           BAAAAAAAAAAAAAAAB,            BAAAAAAAAAAAAAB,             BAAAAAAAAAAAB,              BBAAAAAAABB,                AABBBAA,                AA   AA,,,,,,
            ,,,,,                AA   AA,                AAGGGAA,                AABBBAA,              BBAAAAAAABB,             BAAAAAAAAAAAB,            BAAAAAAAAAAAAAB,           BAAAAAAAAAAAAAAAB,          BAAAAAAAAAAAAAAAAAB,         BAAAAAAABBBBBAAAAAAAB,         BAAAAAAB     BAAAAAAB,      AAAAAAAAAB       BAAAAAAAAA,      AAAAAAAAB         BAAAAAAAA,       GBAAAAAB         BAAAAABG,       GBAAAAAB         BAAAAABG,       GBAAAAAB         BAAAAABG,      AAAAAAAAB         BAAAAAAAA,      AAAAAAAAAB       BAAAAAAAAA,         BAAAAAAB     BAAAAAAB,         BAAAAAAABBBBBAAAAAAAB,          BAAAAAAAAAAAAAAAAAB,           BAAAAAAAAAAAAAAAB,            BAAAAAAAAAAAAAB,             BAAAAAAAAAAAB,              BBAAAAAAABB,                AABBBAA,                AAGGGAA,                AA   AA,,,,,
            ,,,,                AA   AA,                AAEEEAA,                AA   AA,,,,            BB           BB,           BBBBEEAAAAAEEBBBB,           BBBBAA     AABBBB,            BBA         ABB,            EA           AE,     AAA    EA           AE    AAA,     AAA    A             A    AAA,      E     A             A     E,      E     A             ~     E,      E     A             H     E,     AAA    A             I    AAA,     AAA    EA           AE    AAA,            EA           AE,            BBA         ABB,           BBBBAA     AABBBB,           BBBBEEAAAAAEEBBBB,            BB           BB,,,,                AA   AA,                AAEEEAA,                AA   AA,,,,
            ,,,,                AA   AA,                AAGGGAA,,,,,,,             BBBEAAAAAEBBB,             BBAA     AABB,             BA         AB,     AA      EA         AE      AA,     AA      A           A      AA,      G      A           A      G,      G      A           A      G,      G      A           A      G,     AA      A           A      AA,     AA      EA         AE      AA,             BA         AB,             BBAA     AABB,             BBBEAAAAAEBBB,,,,,,,                AAGGGAA,                AA   AA,,,,
            ,,,                AA   AA,                AAEEEAA,                AA   AA,,,,,,,,              BBBAAAAABBB,              BBA     ABB,    AAA       BA       AB       AAA,    AAA       A         A       AAA,     E        A         A        E,     E        A         A        E,     E        A         A        E,    AAA       A         A       AAA,    AAA       BA       AB       AAA,              BBA     ABB,              BBBAAAAABBB,,,,,,,,                AA   AA,                AAEEEAA,                AA   AA,,,
            ,,,                AA   AA,                AAGGGAA,,,,,,,,,,               BBAAAAABB,    AA         BA     AB         AA,    AA         A       A         AA,     G         A       A         G,     G         A       A         G,     G         A       A         G,    AA         A       A         AA,    AA         BA     AB         AA,               BBAAAAABB,,,,,,,,,,                AAGGGAA,                AA   AA,,,
            ,,,                AAEEEAA,                AA   AA,,,,,,,,,,               EBAAAAABE,    AA         BA     AB         AA,    AA         A       A         AA,    E          A       A          E,    E          A       A          E,    E          A       A          E,    AA         A       A         AA,    AA         BA     AB         AA,               EBAAAAABE,,,,,,,,,,                AA   AA,                AAEEEAA,,,
            ,,                AA   AA,                AAGGGAA,                AA   AA,,,,,,,,,,,   AAA          BBFFFBB          AAA,   AAA          BA   AB          AAA,    G           F     F           G,    G           F     F           G,    G           F     F           G,   AAA          BA   AB          AAA,   AAA          BBFFFBB          AAA,,,,,,,,,,,                AA   AA,                AAGGGAA,                AA   AA,,
            ,,                AAEEEAA,                AA   AA,,,,,,,,,,,,   AA           JBFFFBJ           AA,   AA           BA   AB           AA,   E            F     F            E,   E            F     F            E,   E            F     F            E,   AA           BA   AB           AA,   AA           JBFFFBJ           AA,,,,,,,,,,,,                AA   AA,                AAEEEAA,,
            ,,                AAGGGAA,                AA   AA,,,,,,,,,,,,   AA           KDBBBDK           AA,   AA           DBAAABD           AA,   G            BAAAAAB            G,   G            BAAAAAB            G,   G            BAAAAAB            G,   AA           DBAAABD           AA,   AA           KDBBBDK           AA,,,,,,,,,,,,                AA   AA,                AAGGGAA,,
            ,,                AA   AA,                AABBBAA,                  AAA,,,,,,,,,,,   AA                             AA,   AA            DBBBD            AA,    BA           BDEDB           AB,    BA           BEJEB           AB,    BA           BDEDB           AB,   AA            DBBBD            AA,   AA                             AA,,,,,,,,,,,                  AAA,                AABBBAA,                AA   AA,,
            ,                AAGGGAA,                AA   AA,                ABBBBBA,                 AJJJA,,,,,,,,,,,  AAA                             AAA,  AABA                           ABAA,  G BJ                           JB G,  G BJ             F             JB G,  G BJ                           JB G,  AABA                           ABAA,  AAA                             AAA,,,,,,,,,,,                 AJJJA,                ABBBBBA,                AA   AA,                AAGGGAA,
            ,                AA   AA,                AAAAAAA,                BBBBBBB,                AJLBLJA,                  LBL,                   L,                   L,,,,,,,,  AABA                           ABAA,  AABJ                           JBAA,   ABLL                         LLBA,   ABBBLL                     LLBBBA,   ABLL                         LLBA,  AABJ                           JBAA,  AABA                           ABAA,,,,,,,,                   L,                   L,                  LBL,                AJLBLJA,                BBBBBBB,                AAAAAAA,                AA   AA,
            ,                AA   AA,                AAAMAAA,                BBBBBBB,                AJBBBJA,                  BBB,                  LBL,                  LBL,                   F,                   K,,,,,,  AABA                           ABAA,  AABJ                           JBAA,   ABBBLL                     LLBBBA,   MBBBBBFK                 KFBBBBBM,   ABBBLL                     LLBBBA,  AABJ                           JBAA,  AABA                           ABAA,,,,,,                   K,                   F,                  LBL,                  LBL,                  BBB,                AJBBBJA,                BBBBBBB,                AAAMAAA,                AA   AA,
            ,                AA   AA,                AAAAAAA,                BBBBBBB,                AJLBLJA,                  LBL,                   L,                   L,,,,,,,,  AABA                           ABAA,  AABJ                           JBAA,   ABLL                         LLBA,   ABBBLL                     LLBBBA,   ABLL                         LLBA,  AABJ                           JBAA,  AABA                           ABAA,,,,,,,,                   L,                   L,                  LBL,                AJLBLJA,                BBBBBBB,                AAAAAAA,                AA   AA,
            ,                AAGGGAA,                AA   AA,                ABBBBBA,                 AJJJA,,,,,,,,,,,  AAA                             AAA,  AABA                           ABAA,  G BJ                           JB G,  G BJ             F             JB G,  G BJ                           JB G,  AABA                           ABAA,  AAA                             AAA,,,,,,,,,,,                 AJJJA,                ABBBBBA,                AA   AA,                AAGGGAA,
            ,,                AA   AA,                AABBBAA,                  AAA,,,,,,,,,,,   AA                             AA,   AA            DBBBD            AA,    BA           BDEDB           AB,    BA           BEJEB           AB,    BA           BDEDB           AB,   AA            DBBBD            AA,   AA                             AA,,,,,,,,,,,                  AAA,                AABBBAA,                AA   AA,,
            ,,                AAGGGAA,                AA   AA,,,,,,,,,,,,   AA           KDBBBDK           AA,   AA           DBAAABD           AA,   G            BAAAAAB            G,   G            BAAAAAB            G,   G            BAAAAAB            G,   AA           DBAAABD           AA,   AA           KDBBBDK           AA,,,,,,,,,,,,                AA   AA,                AAGGGAA,,
            ,,                AAEEEAA,                AA   AA,,,,,,,,,,,,   AA           JBFFFBJ           AA,   AA           BA   AB           AA,   E            F     F            E,   E            F     F            E,   E            F     F            E,   AA           BA   AB           AA,   AA           JBFFFBJ           AA,,,,,,,,,,,,                AA   AA,                AAEEEAA,,
            ,,                AA   AA,                AAGGGAA,                AA   AA,,,,,,,,,,,   AAA          BBFFFBB          AAA,   AAA          BA   AB          AAA,    G           F     F           G,    G           F     F           G,    G           F     F           G,   AAA          BA   AB          AAA,   AAA          BBFFFBB          AAA,,,,,,,,,,,                AA   AA,                AAGGGAA,                AA   AA,,
            ,,,                AAEEEAA,                AA   AA,,,,,,,,,,               EBAAAAABE,    AA         BA     AB         AA,    AA         A       A         AA,    E          A       A          E,    E          A       A          E,    E          A       A          E,    AA         A       A         AA,    AA         BA     AB         AA,               EBAAAAABE,,,,,,,,,,                AA   AA,                AAEEEAA,,,
            ,,,                AA   AA,                AAGGGAA,,,,,,,,,,               BBAAAAABB,    AA         BA     AB         AA,    AA         A       A         AA,     G         A       A         G,     G         A       A         G,     G         A       A         G,    AA         A       A         AA,    AA         BA     AB         AA,               BBAAAAABB,,,,,,,,,,                AAGGGAA,                AA   AA,,,
            ,,,                AA   AA,                AAEEEAA,                AA   AA,,,,,,,,              BBBAAAAABBB,              BBA     ABB,    AAA       BA       AB       AAA,    AAA       A         A       AAA,     E        A         A        E,     E        A         A        E,     E        A         A        E,    AAA       A         A       AAA,    AAA       BA       AB       AAA,              BBA     ABB,              BBBAAAAABBB,,,,,,,,                AA   AA,                AAEEEAA,                AA   AA,,,
            ,,,,                AA   AA,                AAGGGAA,,,,,,,             BBB AAAAA BBB,             BBAA     AABB,             BA         AB,     AA       A         A       AA,     AA      A           A      AA,      G      A           A      G,      G      A           A      G,      G      A           A      G,     AA      A           A      AA,     AA       A         A       AA,             BA         AB,             BBAA     AABB,             BBB AAAAA BBB,,,,,,,                AAGGGAA,                AA   AA,,,,
            ,,,,                AA   AA,                AAEEEAA,                AA   AA,,,,            BB           BB,           BBBB  AAAAA  BBBB,           BBBBAA     AABBBB,            BBA         ABB,             A           A,     AAA     A           A     AAA,     AAA    A             A    AAA,      E     A             A     E,      E     A             A     E,      E     A             A     E,     AAA    A             A    AAA,     AAA     A           A     AAA,             A           A,            BBA         ABB,           BBBBAA     AABBBB,           BBBBEEAAAAAEEBBBB,            BB           BB,,,,                AA   AA,                AAEEEAA,                AA   AA,,,,
            ,,,,,                AA   AA,                AAGGGAA,                AABBBAA,              BBAAAAAAABB,             BAAAAAAAAAAAB,            BAAAAAAAAAAAAAB,           BAAAAAAAAAAAAAAAB,          BAAAAAAAAAAAAAAAAAB,         BAAAAAAABBBBBAAAAAAAB,         BAAAAAAB     BAAAAAAB,      AAAAAAAAAB       BAAAAAAAAA,      AAAAAAAAB         BAAAAAAAA,       GBAAAAAB         BAAAAABG,       GBAAAAAB         BAAAAABG,       GBAAAAAB         BAAAAABG,      AAAAAAAAB         BAAAAAAAA,      AAAAAAAAAB       BAAAAAAAAA,         BAAAAAAB     BAAAAAAB,         BAAAAAAABBBBBAAAAAAAB,          BAAAAAAAAAAAAAAAAAB,           BAAAAAAAAAAAAAAAB,            BAAAAAAAAAAAAAB,             BAAAAAAAAAAAB,              BBAAAAAAABB,                AABBBAA,                AAGGGAA,                AA   AA,,,,,
            ,,,,,,                AA   AA,                AABBBAA,              BBAAAAAAABB,             BAAAAAAAAAAAB,            BAAAAAAAAAAAAAB,           BAAAAAAAAAAAAAAAB,          BAAAAAAAAAAAAAAAAAB,         BAAAAAAABBBBBAAAAAAAB,         BAAAAAABAAAAABAAAAAAB,       AAAAAAAABAAAAAAABAAAAAAAA,       AAAAAAABAAAAAAAAABAAAAAAA,        BAAAAABAAAAAAAAABAAAAAB,        BAAAAABAAAAAAAAABAAAAAB,        BAAAAABAAAAAAAAABAAAAAB,       AAAAAAABAAAAAAAAABAAAAAAA,       AAAAAAAABAAAAAAABAAAAAAAA,         BAAAAAABAAAAABAAAAAAB,         BAAAAAAABBBBBAAAAAAAB,          BAAAAAAAAAAAAAAAAAB,           BAAAAAAAAAAAAAAAB,            BAAAAAAAAAAAAAB,             BAAAAAAAAAAAB,              BBAAAAAAABB,                AABBBAA,                AA   AA,,,,,,
            ,,,,,,,                AABBBAA,              BBAAAAAAABB,             BAAAAAAAAAAAB,            BAAAAAAAAAAAAAB,           BAAAAAAAAAAAAAAAB,          BAAAAAAAAAAAAAAAAAB,         BAAAAAAABBBBBAAAAAAAB,         BAAAAAABCDDDCBAAAAAAB,        AAAAAAABCEEEEECBAAAAAAA,        AAAAAABCEEBBBEECBAAAAAA,        BAAAAABDEBFFFBEDBAAAAAB,        BAAAAABDEBFFFBEDBAAAAAB,        BAAAAABDEBFFFBEDBAAAAAB,        AAAAAABCEEBBBEECBAAAAAA,        AAAAAAABCEEEEECBAAAAAAA,         BAAAAAABCDDDCBAAAAAAB,         BAAAAAAABBBBBAAAAAAAB,          BAAAAAAAAAAAAAAAAAB,           BAAAAAAAAAAAAAAAB,            BAAAAAAAAAAAAAB,             BAAAAAAAAAAAB,              BBAAAAAAABB,                AABBBAA,,,,,,,
            ,,,,,,,,                AA   AA,                AA   AA,               AAA   AAA,               AAA   AAA,              AAAA   AAAA,             AAAAA   AAAAA,           AAAAAA     AAAAAA,         AAAAAAA       AAAAAAA,         AAAAAA         AAAAAA,,,,         AAAAAA         AAAAAA,         AAAAAAA       AAAAAAA,           AAAAAA     AAAAAA,             AAAAA   AAAAA,              AAAA   AAAA,               AAA   AAA,               AAA   AAA,                AA   AA,                AA   AA,,,,,,,,
            ,,,,,,,,,,                AA   AA,                AA   AA,                AA   AA,               AAA   AAA,              AAA     AAA,           AAAAA       AAAAA,           AAAA         AAAA,,,,           AAAA         AAAA,           AAAAA       AAAAA,              AAA     AAA,               AAA   AAA,                AA   AA,                AA   AA,                AA   AA,,,,,,,,,,
      """;
}
