package com.dishanhai.gt_shanhai.common.machine.structure;

/*** aisles 30~49 */
public class STRData2 {
    public static final String[] D31 = {
        "FFFFFDDDDDCCCCCCCCCCCCCCCCCFDDDDDDDDDDDDDFFFFFFFFC",
        "           BQQQQQQQQQQQQ  B      A A              ",
        "           A            AEA       A               ",
        "           A            EEA       A               ",
        "           A           A          A               ",
        "          BA          AB                          ",
        "            AEE       FB                          ",
        "               AAAAAAAAB                          ",
        "                RA     AB                         ",
        "                BA     AB                         ",
        "                RA     A B                        ",
        "                AA     ANRH                       ",
        "                AA     ANRH                       ",
        "                 E     AAB                        ",
        "                  A    A                          ",
        "                  O    A         B B              ",
        "                  O    AAHB      B B              ",
        "                 BABBBBAAABB     B B              ",
        "                 AANNNNAAAB      B B              ",
        "               BBAA    AAAB      B B              ",
        "               BABA    AAABB     H H              ",
        "               AABBAAAAAABRRG    G G              ",
        "               AA LMMML  B GG    G G              ",
        "               BA LMMML  B GG    G G              ",
        "               BA BMMMB  B       G G              ",
        "               BA  BBB   B       GHG              ",
        "               AA  BLB   B       H H              ",
        "               RA  BLB   B                        ",
        "               BAB BLB   B                        ",
        "                BB BLB   B                        ",
        "                   BLB   B                        ",
        "                   BLB   B                        ",
        "                  BEEEB  B                        ",
        "                  LMMML  B                        ",
        "                  LMMML  B                        ",
        "     K            BMMMB  B                        ",
        "      J           A   AB B                        ",
        "       JA        A     ABB                        ",
        "         A       A     A                          ",
        "          A      A     A                          ",
        "          A      A     A                          ",
        "           A      A   A                           ",
        "            P      AAA                            ",
        "             A    P   P                           ",
        "              A                                   ",
        "               A                                  ",
        "                O                                 ",
        "                 P                                ",
        "                  O                               ",
        "                   OO                             ",
        "                     O                            ",
        "                      O                           ",
        "                      A                           ",
        "                       A                          ",
        "                        AK                        ",
        "                                                  ",
    };

    public static final String[] D32 = {
        "FDDDDDDDDDCCCCCCCCCCCCCCCCCFDDDDDDDDDDDDDFCCCCCCCC",
        "          BQQQQQQQQQQQQQ  B     AANAA             ",
        "          A             A A     AAAAA             ",
        "          A             EEA      AAA              ",
        "          A            A         AAA              ",
        "          A           AB         AAA              ",
        "          AA          FB         BAB              ",
        "          AAKKKKKKKAAAAB         RAR              ",
        "           BKKKKK      AB        BAB              ",
        "           BKKKKK      AB        BHB              ",
        "           BKKKKK      A B       BBB              ",
        "           BBBBBAA     ANB       BHB              ",
        "           GGGG BJ     ANB       BAB              ",
        "                 E     AAB       RAR              ",
        "                  AAAAA          BAB              ",
        "                  OOOOA        EEABAEE            ",
        "                  OOOOA        EEABAEE            ",
        "                 BAAAAAABB     EEABAEE            ",
        "                 EAAAAAABE       B B              ",
        "                 BAAAAAABE                        ",
        "                  AAAAAABE                        ",
        "                  BBBBBBB                         ",
        "                   LLL                            ",
        "                   LRL                            ",
        "                   BBB                            ",
        "                                                  ",
        "                                 G G              ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                   BBB                            ",
        "                   LRL                            ",
        "                   LLL                            ",
        "      K            BBB                            ",
        "       J           AAA                            ",
        "        J         A   AB                          ",
        "         A        A   AR                          ",
        "          A    PPPA   AJ                          ",
        "           A      A   AJ                          ",
        "            P      AAA                            ",
        "             A      P                             ",
        "              ES  PPPPP                           ",
        "               ES   P                             ",
        "                E   H                             ",
        "                 O                                ",
        "                  P                               ",
        "                   O                              ",
        "                    O                             ",
        "                     O                            ",
        "                      O                           ",
        "                      AA                          ",
        "                        AK                        ",
        "                                                  ",
        "                                                  ",
    };

    public static final String[] D33 = {
        "FDDDDDDDDDCCCCCCCCCCCCCCCCCFDDDDDDDDDDDDDFCCCCCCCC",
        "  BBB   R BQQQQQQQQQQQQQ  B  BBBA   ABBB          ",
        "   BAB  R B             A A     A   A             ",
        "    BBB R B             A A     A   A             ",
        "     BAEB B            AEEA     A   A             ",
        "      BB BB           AE        A   A             ",
        "       BB AA          AE        AA AA             ",
        "        BBAN      KAAAAE        AA AA             ",
        "           BKKKKKK AAAAAE       HAAAH             ",
        "           B     K AAAAAE       HAAAH             ",
        "           B     K AAAAA B      HAAAH             ",
        "           BKKKKKKAAAAAANRH     HAAAH             ",
        "           G    EJJAAAAANRH     HAAAH             ",
        "                 EEEEEEAAB      AAAAA             ",
        "                                AAAAA             ",
        "                               EAAAAAE            ",
        "                               EAAAAAE            ",
        "                 BBBBB         EJJJJJE            ",
        "                 EEAAA                            ",
        "                BBBAAA                            ",
        "                   B B                            ",
        "                   B B                            ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                   B B                            ",
        "                   B B                            ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "       K                                          ",
        "        J           B                             ",
        "         A         AAAB                           ",
        "          A        AAAR                           ",
        "           APPP   PAAAJ                           ",
        "            P      AAAJ                           ",
        "             A      P                             ",
        "              SS    H                             ",
        "                S                                 ",
        "                 S                                ",
        "                 S  P                             ",
        "                  O P                             ",
        "                   P                              ",
        "                    O                             ",
        "                     O                            ",
        "                      O                           ",
        "                       O                          ",
        "                        AK                        ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
    };

    public static final String[] D34 = {
        "FDDDDDDDDDCCCCCCCCCCCCCCCCCFDDDDDDDDDDDDDFCCCCCCCC",
        "          BQQQQQQQQQQQQQ  B BBBBA   ABBBB         ",
        "          F             A A    BA   AB            ",
        "          F             A A    BA   AB            ",
        "          F            AEEA    BA   AB            ",
        "          F           A        BA   AB            ",
        "          AA          A        BA   AB            ",
        "          AN      KAAAA        AA   AA            ",
        "           BKKKKKKKN N         AA   AA            ",
        "           B      KN N         NA   AH            ",
        "           B      KN NBBBB     NA   AH            ",
        "           BKKKKKKAABABJJB     NA   AH            ",
        "           G    EEBABABJJB     NA   AH            ",
        "                      BBBB     NA   AH            ",
        "                               NA   AH            ",
        "          BB                   EA   AE            ",
        "         BAA                   EA   AE            ",
        "         BAA                   EJAAAJE            ",
        "         BAA                                      ",
        "          BB   BBB B B                            ",
        "                   A A                            ",
        "                   A A                            ",
        "                   A A                            ",
        "                   A A                            ",
        "                   A A                            ",
        "                   A A                            ",
        "                   A A                            ",
        "                   A A                            ",
        "                   A A                            ",
        "                   B B                            ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "        K                                         ",
        "         K                                        ",
        "          K         B                             ",
        "           K        B                             ",
        "            P     P P                             ",
        "             A      P                             ",
        "              ES    P                             ",
        "                S   H                             ",
        "               NNS                                ",
        "                N S                               ",
        "                  E                               ",
        "                   O                              ",
        "                    P                             ",
        "                     P                            ",
        "                      P                           ",
        "                       P                          ",
        "                        PK                        ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
    };

    public static final String[] D35 = {
        "FDDDDDDDDDCCCCCCCCCCCCCCCCCFDDDDDDDDDDDDDFCCCCCCCC",
        "  BBB   R BQQQQQQQQQQQQQ  B BBHHA   AHHBB         ",
        "   BAB  R B             AAA   HHB   BHH           ",
        "    BBB R B             AAA     B   BO            ",
        "     BAEB B            AEEA     B   B             ",
        "      BB BB           A         B   BO            ",
        "       BB AA          A         A   A             ",
        "        BBAN      KAAAA        BA   AB            ",
        "           BKKKKKKK            BA   AB            ",
        "           BN     K           BAA   AAB           ",
        "           BN     K           BAA   AAB           ",
        "           BKKKKKKB    BB     BAA   AAB           ",
        "           G           BB     BAA   AAB           ",
        "                              BAA   AAB           ",
        "                              BAA   AAB           ",
        "            B                 BA     AB           ",
        "          GEA                  A     A            ",
        "          GBABBB               HAAAAAH            ",
        "          GEA  B                  R               ",
        "            B  BB  B B            H               ",
        "                   B B            H               ",
        "                   A A            R               ",
        "                   A A                            ",
        "                   B B          B   B             ",
        "                   B B         BAGGGAB            ",
        "                   B B          B   B             ",
        "                   A A                            ",
        "                   R R                            ",
        "                   B B                            ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "        K                                         ",
        "         A                                        ",
        "          A                                       ",
        "           A                                      ",
        "            AB                                    ",
        "             P    P                               ",
        "              A                                   ",
        "               ES                                 ",
        "                 S  P                             ",
        "               NN S                               ",
        "              NN  E                               ",
        "              N    A                              ",
        "                    PP                            ",
        "                     O                            ",
        "                      O                           ",
        "                       O                          ",
        "                        O                         ",
        "                         P                        ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
    };

    public static final String[] D36 = {
        "FDDDDDDDDDCCCCCCCCCCCCCCCCCFDDDDDDDDDDDDDFCCCCCCCC",
        "          BBQQQQQQQQQQQQBBB BBHHA   AHHBB         ",
        "           F            AOA   HHB   BHH           ",
        "           F            ANA     B   B             ",
        "           F            AOA     B   BO            ",
        "           F          EEEEA     B   B             ",
        "          BB       EEE          A   A             ",
        "          BB      K            BA   AB            ",
        "            BKKKKKK            BA   AB            ",
        "            NN    K            LMA AML            ",
        "            NN    K            LMA AML            ",
        "            BKKKKKB            LMA AML            ",
        "              B   G            LMA AML            ",
        "              B                LMA AML            ",
        "              B                LMA AML            ",
        "              B                AN   NA            ",
        "            GBB                A     A            ",
        "            GNBB               HAAAAAH            ",
        "            GBB                   B               ",
        "                                  B               ",
        "                                B B B             ",
        "                               BAGBGAB            ",
        "                               RAGBGAR            ",
        "                               BAGGGAB            ",
        "                                EBBBE             ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "        K                                         ",
        "         A  H                                     ",
        "          AAB                                     ",
        "           AAB                                    ",
        "            AB                                    ",
        "             AB                                   ",
        "              P  P                                ",
        "               A                                  ",
        "                E                                 ",
        "                 S  P                             ",
        "                  E                               ",
        "               N   A                              ",
        "             NNN    PP                            ",
        "              N      OPP                          ",
        "           BSB        OOPH                        ",
        "                       OO                         ",
        "                        O                         ",
        "                         O                        ",
        "                          P                       ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
    };

    public static final String[] D37 = {
        "FFFFFFFFDDDCCCCCCCCCCCCCCBBFDDDDDDDDDDDDDFCCCCCCCC",
        "           BBQQQQQQQQQQQB   BBHHA   AHHBB         ",
        "            E                 HHB   BHH           ",
        "            E                   B   BO            ",
        "            E                   B   B             ",
        "            E         EEEEA     B   BO            ",
        "           BB      EEE          A   A             ",
        "          EBB     K            BA   AB            ",
        "             BKKKKK            BA   AB            ",
        "             NN   K           BAA   AAB           ",
        "             NN   K           BAA   AAB           ",
        "             BKKKKB           BAA   AAB           ",
        "                  G           BAA   AAB           ",
        "                              BAA   AAB           ",
        "                              BAA   AAB           ",
        "                              BA     AB           ",
        "            BBB                A     A            ",
        "              NB               HAAAAAH            ",
        "              B                                   ",
        "                                                  ",
        "                               BAGGGAB            ",
        "                                EBBBE             ",
        "                                  B               ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "        K                                         ",
        "         A                                        ",
        "          AA H                                    ",
        "            AB                                    ",
        "             AB                                   ",
        "             AB                                   ",
        "              AB                                  ",
        "               P P                                ",
        "                A                                 ",
        "                 A                                ",
        "                  A                               ",
        "                   AP                             ",
        "                    PP                            ",
        "            NNN      APP                          ",
        "           SNN        OOPH                        ",
        "          BSN B         O                         ",
        "           BSB           O                        ",
        "                         O                        ",
        "                          O                       ",
        "                           P                      ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
    };

    public static final String[] D38 = {
        "CCCCCCCFDDDDCCCCCCCCCCCCCBBFDDDDDDDDDDDDDFCCCCCCCC",
        "            BBQQQQQQQQQQB   BBBBA   ABBBB         ",
        "             H                 BA   AB            ",
        "             H                 BA   AB            ",
        "             H                 BA   AB            ",
        "             H        AAAAA    BA   AB            ",
        "            BB     AAA         BA   AB            ",
        "           EBB    K            AA   AA            ",
        "              BKKKK            AABHBAA            ",
        "              NN  K            BABHBAB            ",
        "              NN  K            HABOBAH            ",
        "              BKKKB            HABHBAH            ",
        "                  G            HABOBAH            ",
        "                               HABHBAH            ",
        "                               HABOBAH            ",
        "               B               HABHBAH            ",
        "            BBGA               BABOBAB            ",
        "            H GA                HAAAH             ",
        "              GA                                  ",
        "               B                                  ",
        "                                B   B             ",
        "                                 BBB              ",
        "                                                  ",
        "                                  B               ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "        K                                         ",
        "         A                                        ",
        "          AA                                      ",
        "            A H                                   ",
        "             AB                                   ",
        "              A                                   ",
        "              A                                   ",
        "               A                                  ",
        "                PP                                ",
        "                 P                                ",
        "                  P                               ",
        "                   P                              ",
        "                    P                             ",
        "                     A                            ",
        "             N        AAPH                        ",
        "          BSNN          O                         ",
        "         BS NNSB         O                        ",
        "          BS S            O                       ",
        "            S             O                       ",
        "                           O                      ",
        "                            P                     ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
    };

    public static final String[] D39 = {
        "CCCCCCCFFDDDDCCCCCCCCCCCCBBFDDDDDDDDDDDDDFCCCCCCCC",
        "             BBQQQQBBBBBB    BBBA   ABBB          ",
        "              F    AAAAAA       A A A             ",
        "              F    AAAAAA       A N A             ",
        "              F    AAAAAA       A N A             ",
        "              F    AAAAAA       A   A             ",
        "             BBAAAA             AAAAA             ",
        "            EBBNNNA             AAAAA             ",
        "               BBBB             HBBBH             ",
        "               BBBB             HN NH             ",
        "               BBBB             H   H             ",
        "               BBBB             H   H             ",
        "               GGGG             H   H             ",
        "                                H   H             ",
        "                                H   H             ",
        "                B               H   H             ",
        "           B   EA               HN NH             ",
        "          GB   BA                HHH              ",
        "           H   EA                                 ",
        "                B                                 ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                 BBB              ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "         K                                        ",
        "          A                                       ",
        "           AA                                     ",
        "             A                                    ",
        "              A                                   ",
        "              A                                   ",
        "               A                                  ",
        "                K                                 ",
        "                 A                                ",
        "                  A                               ",
        "                   A                              ",
        "                    A                             ",
        "                     P                            ",
        "                      A                           ",
        "                       AA                         ",
        "           BSS           O                        ",
        "          BS SB           O                       ",
        "           BSB            O                       ",
        "                           O                      ",
        "                            P                     ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
    };

    public static final String[] D40 = {
        "CCCCCCCCFFDDDDCCCCCCCCCCFBBFFFFFCCCCCFFFFFCCCCCCCC",
        "              BBBBB  B B        AAAAA             ",
        "               B BA  G G        AAAAA             ",
        "               B BA  G G        RAOAR             ",
        "               B BA  G G        RAOAR             ",
        "               B BABBBBBB       RAAAR             ",
        "              BAAAAGGGGGG        GGG              ",
        "             EBAAAA                               ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                B                                 ",
        "               GA                                 ",
        "          GG   GA                                 ",
        "               GA                                 ",
        "                B                                 ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "          K                                       ",
        "           A                                      ",
        "            A                                     ",
        "             A                                    ",
        "              A                                   ",
        "               A                                  ",
        "                K                                 ",
        "                 A                                ",
        "                  AA                              ",
        "                   AA                             ",
        "                    A                             ",
        "                     A                            ",
        "                      P                           ",
        "                       A                          ",
        "                        A                         ",
        "            B            O                        ",
        "           BSB            O                       ",
        "            B              O                      ",
        "                            P                     ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
    };

    public static final String[] D41 = {
        "CCCCCCCCCFFDDDDDDDDDDDDDFBBFCCCFDCCCDFCCCCCCCCCCCC",
        "                                 BAB              ",
        "                                 BAB              ",
        "                                                  ",
        "                                                  ",
        "               B B                                ",
        "                                                  ",
        "               B B                                ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                B                                 ",
        "                B                                 ",
        "                B                                 ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "           K                                      ",
        "            A                                     ",
        "             A                                    ",
        "              A                                   ",
        "               A                                  ",
        "                K                                 ",
        "                 A                                ",
        "                  AA                              ",
        "                    A                             ",
        "                     A                            ",
        "                     A                            ",
        "                      A                           ",
        "                       P                          ",
        "                        A                         ",
        "                         A                        ",
        "                          O                       ",
        "            B              O                      ",
        "                            P                     ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
    };

    public static final String[] D42 = {
        "CCCCCCCCCCFFDDDDDDDDDDDDFBBFCCCFFFFFFFCCCCCCCCCCCC",
        "               G G                                ",
        "               G G                                ",
        "               G G                                ",
        "               B B                                ",
        "                                                  ",
        "               B B                                ",
        "               B B                                ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "            K                                     ",
        "             K                                    ",
        "              K                                   ",
        "               K                                  ",
        "                K                                 ",
        "                 J                                ",
        "                  JA                              ",
        "                    A                             ",
        "                     A                            ",
        "                      A                           ",
        "                      S                           ",
        "                       S                          ",
        "                        P                         ",
        "                         P                        ",
        "                          P                       ",
        "                           P                      ",
        "                            P                     ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
    };

    public static final String[] D43 = {
        "CCCCCCCCCCCFFFDDDDDDDDDDFBBFCCCCCCCCCCCCCCCCCCCCCC",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "               E E                                ",
        "               B B                                ",
        "               B B                                ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                 K                                ",
        "                  J                               ",
        "                   JA                             ",
        "                     A                            ",
        "                      A                           ",
        "                      S                           ",
        "                       S                          ",
        "                        P                         ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
    };

    public static final String[] D44 = {
        "CCCCCCCCCCCCCFDDDDDDDDDDFBBFCCCCCCCCCCCCCCCCCCCCCC",
        "                                                  ",
        "                                                  ",
        "               B B                                ",
        "               A A                                ",
        "               B B                                ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                  K                               ",
        "                   J                              ",
        "                    J                             ",
        "                     J                            ",
        "                      S                           ",
        "                       S                          ",
        "                        P                         ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
    };

    public static final String[] D45 = {
        "CCCCCCCCCCCCCFDDDDDDDDDDFBBFCCCCCCCCCCCCCCCCCCCCCC",
        "                                                  ",
        "               B B                                ",
        "               B B                                ",
        "               B B                                ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                   K                              ",
        "                    J                             ",
        "                     J                            ",
        "                      J                           ",
        "                       S                          ",
        "                        P                         ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
    };

    public static final String[] D46 = {
        "CCCCCCCCCCCCCFDDDDDFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCC",
        "               B B                                ",
        "               A A                                ",
        "               B B                                ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                    K                             ",
        "                     K                            ",
        "                      K                           ",
        "                       K                          ",
        "                        P                         ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
    };

    public static final String[] D47 = {
        "CCCCCCCCCCCCCFDDDDDFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
        "               B B                                ",
        "               B B                                ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
    };

    public static final String[] D48 = {
        "CCCCCCCCCCCCCFDDDDDFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
        "               B B                                ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
    };

    public static final String[] D49 = {
        "CCCCCCCCCCCCCFDDDDDFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
    };

    public static final String[] D50 = {
        "CCCCCCCCCCCCCFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
    };

}