package com.dishanhai.gt_shanhai.common.machine.worldline_cracking;

/*** aisles 60~72 */
public class STRData3 {
    public static final String[] D61 = {
        "BBBBBBBBBBBBBBCCOCCBBBCOCBDLLLDBBBBBBBBBBBDLLLDBCOCBDBCCOCCBBBBBBBBBBBBBB",
        "             H     HHH   H     AAAAA AAAAA     H   H H     H             ",
        "                               GA       AG                               ",
        "                               AAAAAAAAAAA                               ",
        "                                TEAAAAAET                                ",
        "                                  AA AA                                  ",
        "                                  A   A                                  ",
        "                                  A   A                                  ",
        "                                  A   A                                  ",
        "                                  A   A                                  ",
        "                                  A   A                                  ",
        "                                  A   A                                  ",
        "                                  A   A                                  ",
        "                                  AI IA                                  ",
        "                                  AAAAA                                  ",
        "                                  AAAAA                                  ",
        "                                  GEEEG                                  ",
        "                                  G   G                                  ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
    };

    public static final String[] D62 = {
        "BBBBBBBBBBBBBCCCCCBDDBCCCBDDDDDDBBBBBBBBBDDDDDDBCCCBDDBCCCCCBBBBBBBBBBBBB",
        "                  H  H   H     GAAAA AAAAG     H   H  H                  ",
        "                               GA       AG                               ",
        "                               AAAAAAAAAAA                               ",
        "                                TEAAAAAET                                ",
        "                                  A   A                                  ",
        "                                  A   A                                  ",
        "                                  A   A                                  ",
        "                                  A   A                                  ",
        "                                  A   A                                  ",
        "                                  AI IA                                  ",
        "                                  AI IA                                  ",
        "                                  AI IA                                  ",
        "                                  AAAAA                                  ",
        "                                  GQ QG                                  ",
        "                                  GW WG                                  ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
    };

    public static final String[] D63 = {
        "BBBBBBBBBBBBBCOCCBDDDBCOCCBDDDDDBBBBBBBBBDDDDDBCCOCBDDDBCCOCBBBBBBBBBBBBB",
        "                 H   H    H     AAAA AAAA     H    H   H                 ",
        "                                AAAAAAAAA                                ",
        "                                U AAA A U                                ",
        "                                  AAAAA                                  ",
        "                                  GAJAG                                  ",
        "                                  IAJAI                                  ",
        "                                  GAJAG                                  ",
        "                                  GAJAG                                  ",
        "                                  GAJAG                                  ",
        "                                  GAAAG                                  ",
        "                                  GAAAG                                  ",
        "                                  IAAAI                                  ",
        "                                  GAAAG                                  ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
    };

    public static final String[] D64 = {
        "BBBBBBBBBBBBBCCCBDDDDBCCCCCBDDDDBBBBBBBBBDDDDBCCCCCBDDDDBCCCBBBBBBBBBBBBB",
        "                H    H     H    AAAA AAAA    H     H    H                ",
        "                                AAAAAAAAA                                ",
        "                                  A  AA                                  ",
        "                                   ELE                                   ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
    };

    public static final String[] D65 = {
        "BBBBBBBBBBBBBBBBBDDDDDBCCOCCBDDDBBBBBBBBBDDDBCCOCCBDDDDDBBBBBBBBBBBBBBBBB",
        "                      H     H   AAAA AAAA   H     H                      ",
        "                                AAAAAAAAA                                ",
        "                                  EAAAE                                  ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
    };

    public static final String[] D66 = {
        "BBBBBBBBBBBBBBBBBBDDDDDBCCCCCBDDDBBBBBBBDDDBCCCCCBDDDDDBBBBBBBBBBBBBBBBBB",
        "                       H     H   AAA AAA   H     H                       ",
        "                                 AAAAAAA                                 ",
        "                                   AAA                                   ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
    };

    public static final String[] D67 = {
        "BBBBBBBBBBBBBBBBBBBDDDDDBCCOCBDDDBBBBBBBDDDBCOCCBDDDDDBBBBBBBBBBBBBBBBBBB",
        "                        H    H   AAA AAA   H    H                        ",
        "                                 AAAAAAA                                 ",
        "                                   Q Q                                   ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
    };

    public static final String[] D68 = {
        "BBBBBBBBBBBBBBBBBBBBDDDDDBCCCBDDDBBBBBBBDDDBCCCBDDDDDBBBBBBBBBBBBBBBBBBBB",
        "                         H   H   AAAAAAA   H   H                         ",
        "                                   LIL                                   ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
    };

    public static final String[] D69 = {
        "BBBBBBBBBBBBBBBBBBBBBDDDDBCOCBDDDDBBBBBDDDDBCOCBDDDDBBBBBBBBBBBBBBBBBBBBB",
        "                         H   H    ALALA    H   H                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
    };

    public static final String[] D70 = {
        "BBBBBBBBBBBBBBBBBBBBBBDDDBCCCBDDDDBBDBBDDDDBCCCBDDDBBBBBBBBBBBBBBBBBBBBBB",
        "                         H   H    ALILA    H   H                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
    };

    public static final String[] D71 = {
        "BBBBBBBBBBBBBBBBBBBBBBBDDBCOCBDDDDDDDDDDDDDBCOCBDDBBBBBBBBBBBBBBBBBBBBBBB",
        "                         H   H             H   H                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
    };

    public static final String[] D72 = {
        "BBBBBBBBBBBBBBBBBBBBBBBBDBCCCBDDDDDDDDDDDDDBCCCBDBBBBBBBBBBBBBBBBBBBBBBBB",
        "                         H   H             H   H                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
    };

    public static final String[] D73 = {
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
        "                                                                         ",
    };

}